export const ENV = {
    API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
    GOOGLE_CLIENT_ID: import.meta.env.VITE_GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: import.meta.env.VITE_GOOGLE_CLIENT_SECRET,
    GOOGLE_CLIENT_REDIRECT: import.meta.env.VITE_GOOGLE_CLIENT_REDIRECT_URL,
    KAKAO_REST_API_KEY: import.meta.env.VITE_KAKAO_REST_API_KEY,
    KAKAO_JS_KEY: import.meta.env.VITE_KAKAO_JS_KEY,
    COOLSMS_API_KEY: import.meta.env.VITE_COOLSMS_API_KEY,
    COOLSMS_API_SECRET: import.meta.env.VITE_COOLSMS_API_SECRET,
};
